#!/bin/bash

LFS=/mnt/lfs
LFS_TGT=x86_64-lfs-linux-gnu
logfile=log.txt
rundir=$PWD

function log() {
  echo $1 >> $rundir/$logfile
}

function download() {
  cd $LFS/sources
  
  if [ -e $2 ]; then
    echo "$2 already downloaded"
  else
    wget $1
  fi
  
  if [ ! -e $2 ]; then
    echo "failed to download $2"
    exit 1
  fi
}

function extract() {
  directory=$( sed -E "s/\.tar\.[a-z0-9]{2,3}$//" <<< $1 )
  filename=$( basename $1 )
  extension="${filename##*.}"
  cd $LFS/sources
  
  if [ -d $directory ]; then
    rm -rf $directory
  fi
  
  echo extracting $archive
  
  if [ $extension == "bz2" ]; then
    tar -xjf $archive
  fi
  
  if [ ! -d $directory ]; then
    echo $archive does not appear to have unpacked
    exit 1
  fi
}

function checkRetVal() {
  if [ $1 -ne 0 ]; then
    echo "checkRetVal failed"
    log "checkRetVal failed"
    exit 1
  fi
}

function callmake() {
  log "calling make"
  make
  if [ $? -eq 0 ]; then
    log "make ran successfully"
  else
    log "make was unsuccessful"
    exit 1
  fi
}

function callmakeInstall() {
  log "calling make install"
  make
  if [ $? -eq 0 ]; then
    log "make install ran successfully"
  else
    log "make install was unsuccessful"
    exit 1
  fi
}

if [ -e $logfile ]
then
  rm -f $logfile
fi

function BinutilsPass1() {
  ver=2.27
  archiveType=bz2
  program=binutils-$ver
  archive=$program.tar.$archiveType
  url=http://ftp.gnu.org/gnu/binutils/$archive
  section="5.4. Binutils-2.27 - Pass 1"

  log "$section"

  download $url $archive
  extract $archive

  cd $program

  mkdir -v build
  cd build
  checkRetVal $?

  log "starting configure"
  ../configure --prefix=/tools            \
               --with-sysroot=$LFS        \
               --with-lib-path=/tools/lib \
               --target=$LFS_TGT          \
               --disable-nls              \
               --disable-werror

  checkRetVal $?

  callmake

  case $(uname -m) in
    x86_64) mkdir -v /tools/lib && ln -sv lib /tools/lib64 ;;
  esac

  callmakeInstall

  rm -rf $LFS/sources/$program
}

BinutilsPass1


exit 0
